// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ConstantFinder
{
    internal sealed partial class Vsix
    {
        public const string Id = "ConstantFinder.a33aff37-01d7-4a36-9f1a-d612b9b7fd23";
        public const string Name = " ConstantFinder";
        public const string Description = @"Find constants and public static properties with a simple search phrase.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "AgentFire";
        public const string Tags = "search,find,constant,const,static property";
    }
}
